# Build documentation in the docs/ directory with Sphinx
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/source/conf.py
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs