name: Test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v4
    - name: Install smalltime & Dependcies
      run: poetry install
    - name: Run Tests
      run: pytest --cov=./ --cov-report=xml
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true